# Site settings
title: Chicago Young Adult Book Festival
email: chiyabookfest@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Chicago Young Adult Book Festival is an inclusive literary event
  that embraces and promotes the diversity of its urban environment;
  its goal is to engage, enlighten and inspire young readers
  and the authors who write for them.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chiyabookfest.com" # the base hostname & protocol for your site
twitter_username: chiyabookfest
github_username:  chiyabookfest

# Build settings
markdown: kramdown

collections:
- authors
